# Generated by Django 4.2.6 on 2023-10-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slides/')),
                ('audio', models.FileField(upload_to='audio/')),
                ('french_text', models.TextField()),
                ('english_text', models.TextField()),
            ],
        ),
    ]
