# Generated by Django 4.2.6 on 2023-10-07 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_slide_audio_alter_slide_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='audio',
            field=models.FileField(upload_to='static/slides/audio/'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(upload_to='static/slides/img/'),
        ),
    ]
